name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm install
    - name: Build site
      env:
        VUE_APP_API_KEY: ${{ secrets.API_TOKEN }}
      run: npm run build
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: dist
